project_name: proto
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go run ./build/generate.go {{.Version}}
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
      - "-s -w"
      - "-X 'github.com/Blooym/proto/core.Version={{.Version}}'"
      - "-X 'github.com/Blooym/proto/core.Commit={{.Commit}}'"
      - "-X 'github.com/Blooym/proto/core.Date={{.CommitDate}}'"
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      post:
        - env SKIP_COMPRESS={{ if index .Env "SKIP_COMPRESS"  }}{{ .Env.SKIP_COMPRESS }}{{ else }}false{{ end }} sh ./build/scripts/upx.sh {{ .Path }}

archives:
  - format: zip
    files:
      - LICENSE*
      - README*
      - src: ./.build_data/man/*.gz
        dst: manpages/
        strip_parent: true
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"
      - "^ci:"

publishers:
  - name: "packages.blooym.dev"
    dir: "{{ dir .ArtifactPath }}"
    ids:
      - nfpm
    cmd: |
      curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/Blooym/

release:
  github:
    owner: Blooym
    name: proto
  prerelease: auto
