project_name: proto
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go run ./build/generate.go {{.Version}}
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
      - "-s -w"
      - "-X 'github.com/Blooym/proto/core.Version={{.Version}}'"
      - "-X 'github.com/Blooym/proto/core.Commit={{.Commit}}'"
      - "-X 'github.com/Blooym/proto/core.Date={{.CommitDate}}'"
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      post:
        - env SKIP_COMPRESS={{ if index .Env "SKIP_COMPRESS"  }}{{ .Env.SKIP_COMPRESS }}{{ else }}false{{ end }} sh ./build/scripts/upx.sh {{ .Path }}

archives:
  - format: zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - src: ./.build_data/man/*.gz
        dst: manpages/
        strip_parent: true
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"
      - "^ci:"

brews:
  - tap:
      owner: Blooym
      name: proto
    commit_author:
      name: github-actions
      email: actions@github.com
    dependencies:
      - name: gnu-tar
    commit_msg_template: "build: Brew formula update for version {{ .Tag }}"
    description: |
      Proto compatability tool manager
    homepage: "https://github.com/Blooym/proto"
    license: "GPL-3.0-only"

nfpms:
  - vendor: Blooym
    id: nfpm
    homepage: https://github.com/Blooym/proto
    maintainer: Blooym
    description: |
      Proto compatability tool manager
    license: "GPL-3.0"
    priority: extra
    section: Utilities
    formats:
      - deb
      - rpm
    dependencies:
      - tar
    provides:
      - proto
    contents:
      #  Desktop and Store files.
      - src: ./.build_data/dev.blooym.proto.desktop
        dst: /usr/share/applications/dev.blooym.proto.desktop
      - src: ./.build_data/dev.blooym.proto.metainfo.xml
        dst: /usr/share/metainfo/dev.blooym.proto.metainfo.xml

      # Icon files.
      - dst: /usr/share/icons/proto
        type: dir
      - src: ./.build_data/icon.png
        dst: /usr/share/icons/proto/icon.png

      # Man pages.
      - src: ./.build_data/man/
        dst: /usr/share/man/man1/

      # Doc files.
      - dst: /usr/share/doc/proto
        type: dir
      - src: ./LICENSE
        dst: /usr/share/doc/proto/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/proto/README

      # Yum/DNF repository.
      - src: ./.build_data/blooym.repo
        dst: /etc/yum.repos.d/blooym.repo
        type: config|noreplace
        packager: rpm

      # APT repository.
      - src: ./.build_data/blooym.list
        dst: /etc/apt/sources.list.d/blooym.list
        type: config|noreplace
        packager: deb
    rpm:
      compression: xz

publishers:
  - name: "packages.blooym.dev"
    dir: "{{ dir .ArtifactPath }}"
    ids:
      - nfpm
    cmd: |
      curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/Blooym/

release:
  github:
    owner: Blooym
    name: proto
  prerelease: auto
