# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proto < Formula
  desc "Proto compatability tool manager
"
  homepage "https://github.com/BitsOfAByte/proto"
  version "0.12.1"
  license "GPL-3.0-only"

  depends_on "gnu-tar"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/BitsOfAByte/proto/releases/download/v0.12.1/proto_0.12.1_linux_armv6.zip"
      sha256 "a778ed3dc32c235c289aec63fc35d4e9853dcc6beec9cfe96450f58251bd25b0"

      def install
        bin.install "proto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BitsOfAByte/proto/releases/download/v0.12.1/proto_0.12.1_linux_arm64.zip"
      sha256 "0b5200d35e56975e996fc54c8b8b30da45d91ce2df98538f282c6f52fcd8a7c9"

      def install
        bin.install "proto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BitsOfAByte/proto/releases/download/v0.12.1/proto_0.12.1_linux_amd64.zip"
      sha256 "4a585352e3363ba93ea57d060a59a0711a7f654278bc50b7c5aad6a76663535a"

      def install
        bin.install "proto"
      end
    end
  end
end
