# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proto < Formula
  desc "Proto compatability tool manager
"
  homepage "https://github.com/BitsOfAByte/proto"
  version "1.0.0"
  license "GPL-3.0-only"

  depends_on "gnu-tar"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/BitsOfAByte/proto/releases/download/v1.0.0/proto_1.0.0_linux_armv6.zip"
      sha256 "d52d60330feb84599f4298574d451d546076ec06ea506117379f7f06f541ceca"

      def install
        bin.install "proto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BitsOfAByte/proto/releases/download/v1.0.0/proto_1.0.0_linux_arm64.zip"
      sha256 "1936fcd391d064666fb480ace6a725c765308b1d5a58fe8f8379ef7f0396fc36"

      def install
        bin.install "proto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BitsOfAByte/proto/releases/download/v1.0.0/proto_1.0.0_linux_amd64.zip"
      sha256 "176948a73e0ea4a2d40974d6518fb420a17f647d2522e5d4c4b254a83667bfd5"

      def install
        bin.install "proto"
      end
    end
  end
end
