name: "PR: Code Changes"

on:
  pull_request:
    branches: [main]
    types: [ready_for_review, opened, synchronize, reopened]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".goreleaser.yml"

jobs:
  Dependency-Review:
    runs-on: ubuntu-latest
    needs: ["No-Invalid-Edits"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v3

  Preview:
    runs-on: ubuntu-latest
    needs: ["Dependency-Review"]
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: build --clean --snapshot --timeout 60m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_COMPRESS: true

      - name: Upload Assets
        uses: actions/upload-artifact@v3
        with:
          path: |
            dist/proto*_*/*
            checksums.txt
